version: '3'

services:
    file-uploader-app:
        build: .
        volumes:
            - .:/usr/app
        ports:
            - "6500:6500"
    
    
    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password 

    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password 
            - ME_CONFIG_MONGODB_SERVER=mongo
volumes:
    .: