version: '3'
services:
    mongo:
        image: mongo
        ports: 
            - '5500:5500'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password 
        
            
        
    mongo-express:
        image: mongo-express
        ports: 
            - '8081:8081'
        environment:
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password 
            - ME_CONFIG_MONGODB_SERVER=mongo
           
        
        

